### ISSUE TITLE
Some errors while im compiling....

### ISSUE THREAD

**Issue by SenkiTK** [joncampbell123/composite-video-simulator#7]
Sorry for bothering you again....
but when i type"make"to make these files,the "undefined reference to"error occurred.
So i sincerely want u to give me some help!!!THX

![snipaste_2018-07-08_00-50-17](https://user-images.githubusercontent.com/20403019/42412953-0ab18a7c-8249-11e8-84af-9f92362f73b2.png)

**Comment by joncampbell123** [comment]
The program needs to be able to locate the FFMPEG headers and libraries.

You'll need to compile FFMPEG 3.x and put it somewhere, then modify the makefile to add the FFMPEG headers to the include path.

**Comment by SenkiTK** [comment]
But i've put the file foleders the program needs in the same folder with the program..
