### ISSUE TITLE
I‘ve succesfully compiled the files,shall I double click it to use or use it with the command line(ffmpeg)?

### ISSUE THREAD

**Issue by SenkiTK** [joncampbell123/composite-video-simulator#8]
I think it represents that i have completely compiled them all.
![comp](https://user-images.githubusercontent.com/20403019/42723776-a221f4fc-8797-11e8-88f4-b3ce495447a7.png)

i'll appreciate it if you could tell me.

**Comment by SenkiTK** [comment]
And when I run the code,there're some errors like these:
![comp2](https://user-images.githubusercontent.com/20403019/42725504-0e82a14a-87b7-11e8-9524-14f4ca4e1bde.png)

**Comment by joncampbell123** [comment]
The output must be a format that takes PCM audio. Use MOV or AVI.

**Comment by SenkiTK** [comment]
thx...but how can i deal with the unhandled arguments?
![comp3](https://user-images.githubusercontent.com/20403019/42726137-4a13a6f4-87c2-11e8-8898-c339f0cb37eb.png)

**Comment by joncampbell123** [comment]
Specify the output file using -o

So:

-i 3.avi -o 4.avi

**Comment by SenkiTK** [comment]
thx for your help！

**Comment by joncampbell123** [comment]
It worked, correct?
